[package]
name = "dx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# The core file watching library. It provides a cross-platform API.
notify = "6.1.1"

# An asynchronous runtime for writing reliable, network-agnostic applications.
tokio = { version = "1", features = ["full"] }

# Crate for ergonomic error handling.
anyhow = "1.0.86"

# A library for deriving the Error trait.
thiserror = "1.0.61"

# Provides core traits and types for working with asynchronous tasks.
futures = "0.3.30"

# A pure-Rust Git implementation. This is the engine for our Chronicle.
# We enable only the 'index' component feature as per the official documentation.
# The init, discover, and actor functionalities are available through the base crate.
gix = { version = "0.62.0", default-features = false, features = ["index"] }

# A library for handling dates and times, used for our human-readable commit messages.
chrono = "0.4.38"
