[package]
name = "dx"
version = "0.1.0"
edition = "2021"

[dependencies]
notify = "8.1.0"
tokio = { version = "1.46.1", features = ["full"] }
anyhow = "1.0.98"
thiserror = "2.0.12"
futures = "0.3.31"
gix = "0.73.0"
chrono = "0.4.41"