[package]
name = "dx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# The core file watching library. It provides a cross-platform API.
# notify = "6.1.1"
notify = "8.1.0"

# An asynchronous runtime for writing reliable, network-agnostic applications.
# tokio = { version = "1", features = ["full"] }
tokio = "1.46.1"

# Crate for ergonomic error handling.
# anyhow = "1.0.86"
anyhow = "1.0.98"

# A library for deriving the Error trait.
# thiserror = "1.0.61"
thiserror = "2.0.12"

# Provides core traits and types for working with asynchronous tasks.
# futures = "0.3.30"
futures = "0.3.31"

# A pure-Rust Git implementation. This is the engine for our Chronicle.
# We enable only the 'index' component feature as per the official documentation.
# The init, discover, and actor functionalities are available through the base crate.
gix = "0.73.0"

# A library for handling dates and times, used for our human-readable commit messages.
# chrono = "0.4.38"
chrono = "0.4.41"